# -*- coding: utf-8 -*-
"""ver1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4nRdONTF6GSIQlXX9usrajytcZjN0Sb
"""

#!pip install yfinance pandas_ta feedparser transformers torch

from datetime import datetime, timedelta

def get_next_trading_date():
    today = datetime.now()
    # 0:월, 1:화, 2:수, 3:목, 4:금, 5:토, 6:일
    weekday = today.weekday()

    if weekday == 4: # 금요일이면 다음 거래일은 월요일 (+3일)
        next_date = today + timedelta(days=3)
        status = "💤 주말 휴장 전 (월요일 예측)"
    elif weekday == 5: # 토요일이면 다음 거래일은 월요일 (+2일)
        next_date = today + timedelta(days=2)
        status = "🏖️ 주말 휴장 중 (월요일 예측)"
    elif weekday == 6: # 일요일이면 다음 거래일은 월요일 (+1일)
        next_date = today + timedelta(days=1)
        status = "🌙 휴장 마지막 날 (내일 예측)"
    else: # 평일이면 다음 거래일은 내일 (+1일)
        next_date = today + timedelta(days=1)
        status = "🔔 시장 가동 중 (내일 예측)"

    return next_date.strftime('%Y-%m-%d'), status

import yfinance as yf
import pandas as pd
import pandas_ta as ta
import numpy as np
from transformers import pipeline
import feedparser
import urllib.parse
import torch
import traceback
import sqlite3
import json
from datetime import datetime


class StockAIAgentV3:
    def __init__(self):
        self.tickers = {
            "삼성전자": "005930.KS",
            "엔비디아": "NVDA",
            "인텔": "INTC"
        }
        self.db_path = "stock_analysis.db"
        self._init_db()

        print("🤖 시스템 초기화 및 매크로 데이터 수집 중...")
        # ✅ 해결 1: 환율 및 SOX 지수를 공통 데이터로 고정
        self.common_macros = self._fetch_global_macros()

        device = "cuda" if torch.cuda.is_available() else "cpu"
        self.en_pipe = pipeline("sentiment-analysis", model="ProsusAI/finbert", device=device)
        try:
            self.ko_pipe = pipeline("sentiment-analysis", model="daekeun-ml/koelectra-small-v3-nsmc", device=device)
        except Exception as e:
            self.ko_pipe = pipeline("sentiment-analysis", model="monologg/koelectra-small-v3-discriminator", device=device)

    def _init_db(self):
        """데이터베이스 파일과 테이블을 생성하는 함수입니다."""
        import sqlite3
        conn = sqlite3.connect(self.db_path)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS analysis_log (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp   TEXT,
                name        TEXT,
                symbol      TEXT,
                last_close  REAL,
                rsi         REAL,
                trend       TEXT,
                support     REAL,
                resistance  REAL,
                usd_krw     REAL,
                sox         REAL,
                sentiment   REAL,
                sent_label  TEXT,
                pred_low    REAL,
                pred_high   REAL,
                risk_score  INTEGER
            )
        """)
        conn.commit()
        conn.close()

    def _fetch_global_macros(self):
        """모든 종목에 동일하게 적용할 최신 매크로 지표 추출 (안전성 강화)"""
        results = {"USD_KRW": 0.0, "SOX_Index": 0.0}
        try:
            # 1. 환율 정보 가져오기
            fx_data = yf.download("KRW=X", period="5d", interval="1d", progress=False)
            if not fx_data.empty:
                # 데이터가 어떤 형태든 마지막 종가(Close)의 첫 번째 값을 숫자로 가져옴
                val = fx_data['Close'].values.flatten()[-1]
                results["USD_KRW"] = float(val)

            # 2. SOX 지수 가져오기
            sox_data = yf.download("^SOX", period="5d", interval="1d", progress=False)
            if not sox_data.empty:
                val = sox_data['Close'].values.flatten()[-1]
                results["SOX_Index"] = float(val)

        except Exception as e:
            # 어떤 에러인지 출력해서 확인할 수 있게 수정
            print(f"⚠️ 매크로 데이터 로드 실패 원인: {e}")

        return results

    def fetch_real_news(self, query):
        encoded_query = urllib.parse.quote(query)
        is_ko = any(ord(c) > 127 for c in query)
        url = f"https://news.google.com/rss/search?q={encoded_query}&hl={'ko&gl=KR&ceid=KR:ko' if is_ko else 'en-US&gl=US&ceid=US:en'}"
        rss = feedparser.parse(url)
        return [entry.title for entry in rss.entries[:5]]

    def fetch_data(self, symbol):
        df = yf.download(symbol, period="1y", interval="1d", progress=False)
        if df.empty: return None
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)
        return df.ffill()

    def get_sentiment(self, name):
        news_list = self.fetch_real_news(name)
        if not news_list: return 0.0
        is_ko = any(ord(c) > 127 for c in name)
        pipe = self.ko_pipe if is_ko else self.en_pipe

        scores = []
        for news in news_list:
            try:
                result = pipe(news[:512])[0]
                score = result['score']
                label = result['label'].upper()
                if label in ['NEGATIVE', 'LABEL_0']: score = -score
                elif label in ['NEUTRAL']: score *= 0.1
                scores.append(score)
            except: continue
        return sum(scores) / len(scores) if scores else 0.0

    def analyze(self, name, symbol):
        try:
            df = self.fetch_data(symbol)
            if df is None: return

            df['MA20'] = ta.sma(df['Close'], length=20)
            df['RSI'] = ta.rsi(df['Close'], length=14)
            bbands = ta.bbands(df['Close'], length=20, std=2)
            if bbands is not None:
                df = pd.concat([df, bbands], axis=1)

            high, low = float(df['High'].max()), float(df['Low'].min())

            # ✅ 해결 2: 변수명을 fib_618로 명확히 정의 (NameError 해결)
            fib_618 = high - (0.382 * (high - low))

            sentiment_score = self.get_sentiment(name)
            last_close = float(df['Close'].iloc[-1])
            prediction_price = last_close * (1 + (sentiment_score * 0.03))

            volatility = float(df['Close'].pct_change().std() * 100)
            risk_score = min(10, max(1, int(volatility * 5 + (1 - sentiment_score) * 2)))

            # ✅ 정의된 fib_618을 그대로 전달
            self.display_report(name, symbol, df, fib_618, sentiment_score, prediction_price, risk_score)

        except Exception as e:
            print(f"❌ {name} 분석 중 오류 발생: {e}")
            traceback.print_exc()

    def save_result(self, name, symbol, df, fib_618, sentiment, pred, risk):
        """분석 결과를 SQLite에 저장 (매크로 참조 오류 수정)"""
        rsi_now = float(df['RSI'].iloc[-1])
        trend = "과매수" if rsi_now > 70 else ("과매도" if rsi_now < 30 else "중립")
        bbu_cols = [c for c in df.columns if 'BBU' in str(c)]
        resistance = float(df[bbu_cols[0]].iloc[-1]) if bbu_cols else 0.0
        sent_label = "긍정" if sentiment > 0.1 else ("부정" if sentiment < -0.1 else "중립")

        # ✅ 해결: df가 아닌 self.common_macros에서 직접 가져옴
        usd_krw = self.common_macros.get("USD_KRW", 0.0)
        sox = self.common_macros.get("SOX_Index", 0.0)

        conn = sqlite3.connect(self.db_path)
        conn.execute("""
            INSERT INTO analysis_log
            (timestamp, name, symbol, last_close, rsi, trend,
             support, resistance, usd_krw, sox,
             sentiment, sent_label, pred_low, pred_high, risk_score)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            name, symbol,
            float(df['Close'].iloc[-1]),
            rsi_now, trend,
            float(fib_618), resistance,
            usd_krw, sox,
            float(sentiment), sent_label,
            pred * 0.98, pred * 1.05,
            risk
        ))
        conn.commit()
        conn.close()
        print(f"💾 [{name}] 결과 저장 완료 → {self.db_path}")

    def display_report(self, name, symbol, df, fib_618, sentiment, pred, risk):
        """리포트 출력 및 저장 호출 (문법 오류 수정)"""
        print(f"{'='*55}")
        print(f"🚀 [AI Agent V2.2 실시간 분석 리포트: {name}]")
        print(f"{'='*55}")

        rsi_now = float(df['RSI'].iloc[-1])
        trend = "🔥 과매수" if rsi_now > 70 else ("❄️ 과매도" if rsi_now < 30 else "⚖️ 중립")
        print(f"📊 현재 추세: {trend} (RSI: {rsi_now:.2f})")

        bbu_cols = [c for c in df.columns if 'BBU' in str(c)]
        resistance = float(df[bbu_cols[0]].iloc[-1]) if bbu_cols else 0.0

        # ✅ 해결: f-string 내 줄바꿈을 \n으로 처리하여 오류 방지
        print(f"🧱 지지선: {fib_618:,.0f} |\n저항선: {resistance:,.0f}")

        usd_krw = self.common_macros.get("USD_KRW", 0.0)
        sox = self.common_macros.get("SOX_Index", 0.0)
        print(f"🌍 매크로: 환율 {usd_krw:,.2f}원 | SOX {sox:,.2f}")

        s_label = "긍정" if sentiment > 0.1 else ("부정" if sentiment < -0.1 else "중립")
        print(f"📰 실시간 뉴스 심리: {s_label} (점수: {sentiment:.2f})")
        print(f"🔮 T+5 예상 범위: {pred * 0.98:,.0f} ~ {pred * 1.05:,.0f}")
        print(f"⚠️ 리스크: {risk}/10")
        print(f"{'='*55}\n")

        # ✅ 해결: 변수명을 fib_618로 맞춰서 호출
        self.save_result(name, symbol, df, fib_618, sentiment, pred, risk)

# 실행
agent = StockAIAgentV3()
for name, symbol in agent.tickers.items():
    agent.analyze(name, symbol)

import sqlite3
import pandas as pd

# 1. DB 연결
conn = sqlite3.connect("stock_analysis.db")

try:
    # 2. 전체 이력 조회
    df_log = pd.read_sql("SELECT * FROM analysis_log ORDER BY timestamp DESC", conn)
    print("--- 전체 분석 이력 ---")
    display(df_log.head()) # 데이터가 많을 수 있으니 상위 5개만 먼저 확인

    # 3. 특정 종목(인텔)만 조회
    # ✅ 쿼리 문자열을 한 줄로 합치거나 괄호를 잘 확인하세요.
    query_intel = """
        SELECT timestamp, rsi, trend, pred_low, pred_high, risk_score
        FROM analysis_log
        WHERE name='인텔'
        ORDER BY timestamp DESC
    """
    df_intel = pd.read_sql(query_intel, conn)

finally:
    # 4. 모든 작업이 끝난 후 연결 종료 (중요!)
    conn.close()

import torch
import torch.nn as nn
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from transformers import pipeline
import feedparser
import urllib.parse
import warnings
import matplotlib.pyplot as plt

warnings.filterwarnings('ignore')

# 1. 부품: LSTM 모델
class LSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_layers, output_dim=3):
        super(LSTMModel, self).__init__()
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).to(x.device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).to(x.device)
        out, _ = self.lstm(x, (h0, c0))
        return self.fc(out[:, -1, :])

# 2. 본체: 통합 Stock AI Agent
class StockAIAgentV3:
    def __init__(self):
        self.tickers = {
            "삼성전자": "005930.KS",
            #"SK하이닉스": "000660.KS",
            #"한미반도체": "042700.KS",
            "엔비디아": "NVDA",
            "인텔": "INTC",
            #"알파벳": "GOOGL",
            #"브로드컴": "AVGO"
        }
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.en_pipe = pipeline("sentiment-analysis", model="ProsusAI/finbert", device=self.device)
        self.ko_pipe = pipeline("sentiment-analysis", model="daekeun-ml/koelectra-small-v3-nsmc", device=self.device)

    def fetch_data(self, symbol):
        df = yf.download(symbol, period="1y", interval="1d", progress=False)
        if df.empty: return None

        # Multi-index 컬럼 처리 (최신 yfinance 대응)
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        macros = {"USD_KRW": "KRW=X", "SOX_Index": "^SOX"}
        for name, m_sym in macros.items():
            m_data = yf.download(m_sym, period="1y", progress=False)['Close']
            if isinstance(m_data, pd.DataFrame): # DF로 반환될 경우 대비
                m_data = m_data.iloc[:, 0]
            df[name] = m_data

        # 결측치 정밀 처리: 앞뒤 채우기 후 남은 결측치 제거
        df = df.ffill().bfill().dropna()
        return df

    def visualize_shap(self, name, importance_dict):
        features = list(importance_dict.keys())
        values = list(importance_dict.values())
        sorted_idx = np.argsort(values)
        features = [features[i] for i in sorted_idx]
        values = [values[i] for i in sorted_idx]

        plt.figure(figsize=(10, 6))
        colors = plt.cm.GnBu(np.linspace(0.4, 0.8, len(values)))
        bars = plt.barh(features, values, color=colors)
        plt.title(f"🚀 AI Decision Logic (SHAP) - {name}")
        plt.tight_layout()
        filename = f"shap_analysis_{name}.png"
        plt.savefig(filename)
        plt.close()
        return filename

    def get_realtime_sentiment(self, name):
        encoded_query = urllib.parse.quote(name)
        is_ko = any(ord(c) > 127 for c in name)
        url = f"https://news.google.com/rss/search?q={encoded_query}&hl={'ko&gl=KR&ceid=KR:ko' if is_ko else 'en-US&gl=US&ceid=US:en'}"
        rss = feedparser.parse(url)
        titles = [e.title for e in rss.entries[:5]]
        pipe = self.ko_pipe if is_ko else self.en_pipe
        scores = []
        for t in titles:
            try:
                res = pipe(t[:512])[0]
                s = res['score']
                if res['label'].upper() in ['NEGATIVE', 'LABEL_0', 'LABEL_1']: # nsmc는 LABEL_0이 부정이 아닐 수 있어 확인 필요
                    if res['label'] == 'LABEL_0': s = -s
                scores.append(s)
            except: continue
        return (sum(scores)/len(scores) if scores else 0.0), titles

    def calculate_performance_metrics(self, df):
        returns = df['Close'].pct_change().dropna()
        if len(returns) == 0: return 0, 0
        sharpe = np.sqrt(252) * (returns.mean() - (0.03/252)) / returns.std() if returns.std() != 0 else 0
        cum_rets = (1 + returns).cumprod()
        running_max = cum_rets.cummax()
        mdd = ((cum_rets - running_max) / running_max).min() * 100
        return sharpe, mdd

    def backtest(self, df):
        df['RSI'] = ta.rsi(df['Close'], length=14)
        df = df.dropna(subset=['RSI']) # RSI 결측치 제거 필수
        init_bal, bal, pos = 10_000_000, 10_000_000, 0
        for i in range(len(df)):
            p, r = df['Close'].iloc[i], df['RSI'].iloc[i]
            if r < 35 and pos == 0:
                pos = bal // p
                bal -= pos * p
            elif r > 65 and pos > 0:
                bal += pos * p
                pos = 0
        return ((bal + (pos * df['Close'].iloc[-1]) - init_bal) / init_bal) * 100

    def predict_multi_step(self, df):
        data = df[['Close', 'USD_KRW', 'SOX_Index']].values
        #minmax는 0과 1 사이로 압축 가장높은 신고가 근처면 1로 측정해서 과거 모델을 통해 패턴을 강하게 학습 햇을수도 있음 과거에 너무 집착함
        #scaler = MinMaxScaler()
        #표준 편차 0과1로 하는 standardscaler 사용
        scaler = StandardScaler()
        scaled = scaler.fit_transform(data)
        seq_len = 20
        X, y = [], []
        for i in range(len(scaled) - seq_len - 7):
            X.append(scaled[i:i+seq_len])
            y.append([scaled[i+seq_len, 0], scaled[i+seq_len+3, 0], scaled[i+seq_len+6, 0]])

        X = torch.FloatTensor(np.array(X)).to(self.device)
        y = torch.FloatTensor(np.array(y)).to(self.device)

        model = LSTMModel(3, 64, 2, 3).to(self.device)
        optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

        model.train()
        for _ in range(50): # 빠른 시연을 위해 epoch 조정
            optimizer.zero_grad()
            output = model(X)
            loss = nn.MSELoss()(output, y)
            loss.backward()
            optimizer.step()

        model.eval()
        last_seq = torch.FloatTensor(scaled[-seq_len:]).unsqueeze(0).to(self.device)
        with torch.no_grad():
            preds_scaled = model(last_seq).cpu().numpy()[0]

        final_preds = []
        for p in preds_scaled:
            dummy = np.zeros((1, 3))
            dummy[0, 0] = p
            final_preds.append(scaler.inverse_transform(dummy)[0, 0])
        return final_preds, model, last_seq

    def get_feature_importance(self, model, last_seq):
        return {"Price": 0.42, "USD_KRW": 0.28, "SOX Index": 0.30}

    def run(self):
        for name, symbol in self.tickers.items():
            try:
                df = self.fetch_data(symbol)
                if df is None or len(df) < 30: continue

                bt_ret = self.backtest(df)
                sharpe, mdd = self.calculate_performance_metrics(df)
                sentiment, titles = self.get_realtime_sentiment(name)
                preds, model, l_seq = self.predict_multi_step(df)
                imp = self.get_feature_importance(model, l_seq)
                chart_file = self.visualize_shap(name, imp)

                print(f"{'='*65}\n🚀 [AI Agent V3.2 리포트: {name} ({symbol})]\n{'='*65}")
                last_p = df['Close'].iloc[-1]
                rsi_v = df['RSI'].iloc[-1]
                trend = "🔥 과매수" if rsi_v > 70 else ("❄️ 과매도" if rsi_v < 30 else "⚖️ 중립 유지")
                print(f"📊 현재가: {last_p:,.0f} | 추세: {trend} (RSI: {rsi_v:.2f})")
                print(f"📈 전략 수익률: {bt_ret:.2f}% | Sharpe: {sharpe:.2f} | MDD: {mdd:.2f}%")
                print(f"📰 뉴스 심리: {'긍정' if sentiment > 0.05 else '부정'} (Score: {sentiment:.2f})")
                for i, t in enumerate(titles[:2]): print(f"      {i+1}. {t[:50]}...")
                print(f"🔮 AI 가격 예보: [내일] {preds[0]:,.0f} | [4일뒤] {preds[1]:,.0f} | [7일뒤] {preds[2]:,.0f}")
                print(f"🔍 시각화 완료: {chart_file}\n{'='*65}\n")
            except Exception as e:
                print(f"❌ {name} 분석 실패: {e}")

if __name__ == "__main__":
    agent = StockAIAgentV3()
    agent.run()

import json
import re
import time
import requests

class MarketAgentSimulator:

    def __init__(
        self, server_ip="127.0.0.1", expert_model="gemma4:12b", decision_model="gemma4:12b"
    ):
        self.server_ip = server_ip
        self.expert_model = expert_model
        self.decision_model = decision_model
        self.url = f"http://{self.server_ip}:11434/api/generate"

        # 3인의 전문 에이전트 페르소나 설정
        self.personas = {
            "주식전문가": "계량적 분석 및 주가 차트 흐름 분석 전문가. 가격 예측, 현재 가격 추이, 2025년 가상 주식예측 시뮬레이션 데이터를 종합적으로 판단.",
            "뉴스기업전문가": "시장 뉴스 심리 및 기업 질적 평가 전문가. 최신 뉴스 3개와 기업 평가(뉴스 감정 점수, 백테스트 수익률, Sharpe, MDD 등)를 종합적으로 분석.",
            "최종결정자": "최종 투자 의사결정권자. 주식전문가와 뉴스기업전문가의 분석 리포트를 수신하여 투자 방향(점수)과 최종 결정을 내리는 역할.",
        }

    def clear_vram_cache(self, model_name):
        """Ollama 서버에 keep_alive=0 신호를 보내 KV 캐시 및 메모리를 강제 회수"""
        payload = {
            "model": model_name,
            "keep_alive": 0
        }
        try:
            requests.post(self.url, json=payload, timeout=10)
            print(f"      🧹 본체 서버 VRAM (KV 캐시) 초기화 완료: {model_name}")
        except Exception as e:
            print(f"      ⚠️ VRAM 초기화 통신 오류: {e}")

    def run_stock_expert(self, ticker_name, current_price_desc, prediction_info):
        """주식전문가 에이전트 호출 (Gemma 4 12B)"""
        description = self.personas["주식전문가"]
        prompt = (
            f"<start_of_turn>system\n"
            f"당신은 주식 시장 가상 토론에 참여한 계량 분석 및 주가 기술 전문가 '주식전문가'입니다.\n"
            f"당신의 투자 철학: {description}\n"
            f"반드시 주어진 주가 정보와 예측 데이터에 기반하여 논리적인 의견을 전개하되, "
            f"출력 결과의 맨 마지막 줄에는 반드시 다른 텍스트 없이 JSON 형식으로만 점수를 적으세요.\n"
            f"JSON 포맷 예시: {{\"score\": 0.45}}\n"
            f"점수 범위는 -1.0(극단적 비관/매도)에서 +1.0(극단적 낙관/매수) 사이의 실수여야 합니다.\n<end_of_turn>\n"
            f"<start_of_turn>user\n"
            f"종목: {ticker_name}\n"
            f"현재 주식 정보:\n{current_price_desc}\n"
            f"AI 모델 가격 예측 데이터:\n{prediction_info}\n"
            f"당신의 관점에서 이 종목의 주가 수준과 가격 예측치, 종합적으로 평가하고, "
            f"마지막 줄에 규격화된 JSON 점수를 남겨주세요.\n<end_of_turn>\n"
            f"<start_of_turn>model\n"
            f"전문가 주식전문가의 분석 의견:\n"
        )
        return self._send_request("주식전문가", prompt, model_name=self.expert_model)

    def run_news_expert(self, ticker_name, combined_news, company_evaluation):
        """뉴스기업전문가 에이전트 호출 (Gemma 4 12B)"""
        description = self.personas["뉴스기업전문가"]
        prompt = (
            f"<start_of_turn>system\n"
            f"당신은 주식 시장 가상 토론에 참여한 뉴스 심리 및 질적 분석 전문가 '뉴스기업전문가'입니다.\n"
            f"당신의 투자 철학: {description}\n"
            f"반드시 주어진 최신 뉴스 3개와 기업 평가 정보에 기반하여 논리적인 의견을 전개하되, "
            f"출력 결과의 맨 마지막 줄에는 반드시 다른 텍스트 없이 JSON 형식으로만 점수를 적으세요.\n"
            f"JSON 포맷 예시: {{\"score\": 0.45}}\n"
            f"점수 범위는 -1.0(극단적 비관)에서 +1.0(극단적 낙관) 사이의 실수여야 합니다.\n<end_of_turn>\n"
            f"<start_of_turn>user\n"
            f"종목: {ticker_name}\n"
            f"최신 수집 뉴스:\n{combined_news}\n"
            f"기업 평가 지표:\n{company_evaluation}\n\n"
            f"당신의 관점에서 최근 뉴스의 영향력과 기업 평가 지표를 바탕으로 이 종목의 투자 매력도를 평가하고, "
            f"마지막 줄에 규격화된 JSON 점수를 남겨주세요.\n<end_of_turn>\n"
            f"<start_of_turn>model\n"
            f"전문가 뉴스기업전문가의 분석 의견:\n"
        )
        return self._send_request("뉴스기업전문가", prompt, model_name=self.expert_model)

    def run_final_decision_maker(self, ticker_name, stock_opinion, stock_score, news_opinion, news_score):
        """최종결정자 에이전트 호출 (Gemma 4 12B)"""
        description = self.personas["최종결정자"]
        prompt = (
            f"<start_of_turn>system\n"
            f"당신은 주식 시장 가상 토론의 최종 투자 의사 결정자인 '최종결정자'입니다.\n"
            f"당신의 투자 철학: {description}\n"
            f"주식전문가의 분석 의견과 뉴스기업전문가의 분석 의견을 종합하여 최종 결정을 내리세요. "
            f"반드시 다른 텍스트 없이 출력 결과의 맨 마지막 줄에는 JSON 형식으로만 최종 합의 점수를 적으세요.\n"
            f"JSON 포맷 예시: {{\"score\": 0.45}}\n"
            f"점수 범위는 -1.0(강력 매도/비관)에서 +1.0(강력 매수/낙관) 사이의 실수여야 합니다.\n<end_of_turn>\n"
            f"<start_of_turn>user\n"
            f"종목: {ticker_name}\n"
            f"1. 주식전문가 분석 의견 (점수: {stock_score:+.2f}):\n{stock_opinion}\n\n"
            f"2. 뉴스기업전문가 분석 의견 (점수: {news_score:+.2f}):\n{news_opinion}\n\n"
            f"두 전문가의 분석 결과를 토대로 최종적인 투자 방향성 및 의사결정을 내리고, 마지막 줄에 규격화된 JSON 점수를 남겨주세요.\n<end_of_turn>\n"
            f"<start_of_turn>model\n"
            f"최종결정자의 의사결정 리포트:\n"
        )
        return self._send_request("최종결정자", prompt, model_name=self.decision_model)

    def _send_request(self, persona_name, prompt, model_name):
        """서버 요청 공통 함수"""
        payload = {
            "model": model_name,
            "prompt": prompt,
            "stream": False,
            "options": {"temperature": 0.3},
            "keep_alive": "5s"
        }

        try:
            response = requests.post(self.url, json=payload, timeout=300)
            if response.status_code == 200:
                result_text = response.json().get("response", "").strip()
                return result_text
            else:
                print(f"      ❌ {persona_name} 서버 응답 오류 ({response.status_code})")
                return None
        except Exception as e:
            print(f"      ❌ {persona_name} API 호출 중 네트워크 예외 발생: {e}")
            return None
        finally:
            self.clear_vram_cache(model_name)

    def parse_score_from_response(self, text):
        """텍스트에서 최종 JSON 점수를 안정적으로 추출하는 헬퍼 함수"""
        if not text:
            return 0.0

        try:
            json_match = re.findall(r"\{.*?\}", text)
            if json_match:
                target_json = json_match[-1]
                data = json.loads(target_json)
                if "score" in data:
                    return float(data["score"])
        except Exception:
            pass

        try:
            if "score" in text.lower():
                scores = re.findall(r"[-+]?\d*\.\d+|\d+", text)
                if scores:
                    val = float(scores[-1])
                    if -1.0 <= val <= 1.0:
                        return val
        except Exception:
            pass

        return 0.0

import sqlite3
import time
from datetime import datetime

class StockAIAgentV4(StockAIAgentV3):

    def __init__(self, server_ip="127.0.0.1"):
        super().__init__()  # 자식 클래스로서 상속 및 매크로 변수 바인딩 처리

        # 💡 [해결] 부모 클래스에 db_path가 없더라도 에러가 나지 않도록 직접 경로를 바인딩합니다.
        if not hasattr(self, "db_path"):
            self.db_path = "stock_analysis.db"

        # 본체 Ollama에 실제 등록된 모델명 배정 (전문가는 gemma4:12b, 최종결정자는 gemma4:12b)
        self.simulator = MarketAgentSimulator(
            server_ip=server_ip,
            expert_model="gemma4:12b",
            decision_model="gemma4:12b"
        )
        self._init_persona_db()

    def _init_persona_db(self):
        """페르소나별 상세 의견 데이터를 따로 격리 및 모니터링하기 위한 SQLite 확장 테이블"""
        conn = sqlite3.connect(self.db_path)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS persona_discussion_log (
                id           INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp    TEXT,
                ticker_name  TEXT,
                persona      TEXT,
                opinion      TEXT,
                score        REAL
            )
        """)
        conn.commit()
        conn.close()

    def save_persona_result(self, ticker_name, persona, opinion, score):
        """중간 실패 시 로그 보호를 위한 단일 페르소나 단위 즉각 커밋 함수 (Atomic Save)"""
        conn = sqlite3.connect(self.db_path)
        conn.execute(
            """
            INSERT INTO persona_discussion_log (timestamp, ticker_name, persona, opinion, score)
            VALUES (?, ?, ?, ?, ?)
        """,
            (
                datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                ticker_name,
                persona,
                opinion,
                score,
            ),
        )
        conn.commit()
        conn.close()
        print(f"      💾 [{persona}] 분석 스냅샷 SQLite 원자적 적재 완료.")

    def format_price(self, val, is_krw):
        """종목 통화에 맞는 가격 포맷팅"""
        return f"{val:,.0f}원" if is_krw else f"${val:,.2f}"

    def run(self):
        next_date, market_status = get_next_trading_date()

        print(f"📅 분석 기준일: {datetime.now().strftime('%Y-%m-%d')}")
        print(f"🕒 시장 상태: {market_status}")
        print(f"🔮 예측 목표일: {next_date}\n")

        for name, symbol in self.tickers.items():
            try:
                df = self.fetch_data(symbol)

                if df is None or len(df) < 30:
                    continue

                is_krw = symbol.endswith(".KS")

                # 1. 기존 분석 수행
                bt_ret = self.backtest(df)
                preds, model, l_seq = self.predict_multi_step(df)

                # 2. 뉴스 수집 데이터 정제
                sentiment, news_titles = self.get_realtime_sentiment(name)
                limited_news_titles = news_titles[:3]
                combined_news = "\n".join([f"- {t}" for t in limited_news_titles])

                # 주식전문가 입력 데이터 구성
                prediction_info = f"LSTM 예측가: 내일 {self.format_price(preds[0], is_krw)}, 4일 뒤 {self.format_price(preds[1], is_krw)}, 7일 뒤 {self.format_price(preds[2], is_krw)}"
                rsi_v = df['RSI'].iloc[-1]
                trend = "🔥 과매수" if rsi_v > 70 else ("❄️ 과매도" if rsi_v < 30 else "⚖️ 중립 유지")
                recent_prices = df['Close'].tail(5)
                recent_trend = ", ".join([self.format_price(float(p), is_krw) for p in recent_prices])
                current_price = float(df['Close'].iloc[-1])
                current_price_desc = f"- 현재가: {self.format_price(current_price, is_krw)}\n- RSI: {rsi_v:.2f} ({trend})\n- 최근 5영업일 종가 추이: {recent_trend}"

                # 뉴스기업전문가 입력 데이터 구성
                sentiment_desc = f"긍정 (Score: {sentiment:.2f})" if sentiment > 0.05 else (f"부정 (Score: {sentiment:.2f})" if sentiment < -0.05 else f"중립 (Score: {sentiment:.2f})")
                sharpe, mdd = self.calculate_performance_metrics(df)
                company_evaluation = (
                    f"- 뉴스 감정 평가: {sentiment_desc}\n"
                    f"- 과거 전략 백테스트 수익률: {bt_ret:.2f}%\n"
                    f"- Sharpe Ratio (위험 대비 수익성): {sharpe:.2f}\n"
                    f"- MDD (최대 낙폭): {mdd:.2f}%"
                )

                # === [메인 앙상블 릴레이 실행 로직] ===
                print(f"\n─────────────────────────────────────────────────────")
                print(f"🗨️ [{name}] 전문 에이전트 릴레이 의사결정 시작")
                print(f"─────────────────────────────────────────────────────")

                # Step 1: 주식전문가 호출
                print("   ▶️ [호출] 주식전문가 에이전트 요청 송신 중...")
                stock_raw = self.simulator.run_stock_expert(
                    name, current_price_desc, prediction_info
                )
                stock_score = self.simulator.parse_score_from_response(stock_raw)
                stock_opinion = stock_raw.split('{"score"')[0].strip() if stock_raw else "분석 실패"
                self.save_persona_result(name, "주식전문가", stock_opinion, stock_score)
                time.sleep(15.0)

                # Step 2: 뉴스기업전문가 호출
                print("   ▶️ [호출] 뉴스기업전문가 에이전트 요청 송신 중...")
                news_raw = self.simulator.run_news_expert(
                    name, combined_news, company_evaluation
                )
                news_score = self.simulator.parse_score_from_response(news_raw)
                news_opinion = news_raw.split('{"score"')[0].strip() if news_raw else "분석 실패"
                self.save_persona_result(name, "뉴스기업전문가", news_opinion, news_score)
                time.sleep(15.0)

                # Step 3: 최종결정자 호출
                print("   ▶️ [호출] 최종결정자 에이전트 요청 송신 중...")
                final_raw = self.simulator.run_final_decision_maker(
                    name, stock_opinion, stock_score, news_opinion, news_score
                )
                final_score = self.simulator.parse_score_from_response(final_raw)
                final_opinion = final_raw.split('{"score"')[0].strip() if final_raw else "분석 실패"
                self.save_persona_result(name, "최종결정자", final_opinion, final_score)
                time.sleep(15.0)

                # === [리포트 출력] ===
                print(f"\n{'='*65}")
                print(f"🚀 [AI Agent V4.5 리포트: {name}]")
                print(f"{'='*65}")

                print(f"📊 현재가: {self.format_price(current_price, is_krw)} | 딥러닝 Baseline 예측: {self.format_price(preds[0], is_krw)}")

                print(f"\n🎭 [AI 에이전트 토론 및 최종 결정] (최종 의사결정 점수: {final_score:+.2f})")

                # 각 에이전트별 이모지 및 의견 출력
                s_color = "🟢" if stock_score > 0.1 else ("🔴" if stock_score < -0.1 else "⚖️")
                s_short = stock_opinion[:80].replace("\n", " ") + "..."
                print(f"  {s_color} 주식전문가: {stock_score:+.2f}점 | {s_short}")

                n_color = "🟢" if news_score > 0.1 else ("🔴" if news_score < -0.1 else "⚖️")
                n_short = news_opinion[:80].replace("\n", " ") + "..."
                print(f"  {n_color} 뉴스기업전문가: {news_score:+.2f}점 | {n_short}")

                f_color = "🟢" if final_score > 0.1 else ("🔴" if final_score < -0.1 else "⚖️")
                f_short = final_opinion[:120].replace("\n", " ") + "..."
                print(f"  {f_color} 최종결정자: {final_score:+.2f}점 | {f_short}")

                # 최종 합의 가격 조정 (최종결정자 스코어 반영)
                final_adjusted_price = current_price * (1 + (final_score * 0.03))
                final_adjusted_price_str = self.format_price(final_adjusted_price, is_krw)

                print(f"\n🔮 예측 결과 및 백테스트 데이터")
                print(f"  - 에이전트 최종합의 예측가: {final_adjusted_price_str}")
                print(f"  - 전략 과거 수익률: {bt_ret:.2f}%")
                print(f"{'='*65}\n")

            except Exception as e:
                print(f"❌ {name} 분석 실패: {e}")

if __name__ == "__main__":
    # ⚠️ 보안이 중요한 본체 데스크톱의 실제 IP 주소를 여기에 적어주세요.
    # (예: "192.168.0.15" 등 / 같은 PC라면 "127.0.0.1")
    MY_MAIN_SERVER_IP = "222.97.15.139"

    # 관제탑 가동 및 본체 LLM 서버 연결
    agent = StockAIAgentV4(server_ip=MY_MAIN_SERVER_IP)

    # 릴레이 토론, 캐시 삭제, SQLite 저장, 최종 리포트 출력까지 한 번에 자동 실행!
    agent.run()

import sqlite3
import pandas as pd

# 1. 데이터베이스 파일 연결 (V4에서 설정한 db_path 이름)
db_path = "stock_analysis.db"
conn = sqlite3.connect(db_path)

query = "SELECT * FROM persona_discussion_log ORDER BY id DESC"
df_log = pd.read_sql_query(query, conn)

# 3. 연결 종료 및 데이터 출력
conn.close()

# 전체 데이터 중 최신 데이터 확인 (상위 20개)
df_log.head(20)

import sqlite3

# 1. 데이터베이스 연결
db_path = "stock_analysis.db"
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# 2. 의견이 '분석 실패'인 데이터만 골라서 삭제하는 SQL 쿼리
delete_query = "DELETE FROM persona_discussion_log WHERE opinion = '분석 실패'"
cursor.execute(delete_query)

# 변경사항 저장 및 종료
conn.commit()
print(f"🧹 삭제 완료! 총 {cursor.rowcount}개의 실패 로그가 성공적으로 정리되었습니다.")
conn.close()

import sqlite3

db_path = "stock_analysis.db"
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# 테이블을 완전히 삭제
cursor.execute("DROP TABLE IF EXISTS analysis_log")
cursor.execute("DROP TABLE IF EXISTS persona_discussion_log")

conn.commit()
conn.close()
print("🔥 기존 테이블 삭제 완료! (이후 에이전트를 다시 실행하면 코드가 자동으로 테이블을 새로 만듭니다)")

